### ISSUE TITLE
Modify `dndR` Website

### ISSUE THREAD

**Issue by njlyon0** [njlyon0/dndR#7]
## Motivation

Having the website be in the package repo is nice for keeping my list of repositories svelte and for keeping all `dndR` stuff in the same place. However, it has some downsides that are becoming cumbersome:

1. Stops README from "knitting", instead it "renders" (unless you run `rmarkdown::render("README.Rmd")` which is annoying
    - Rendering creates a "README.html" and a weird Quarto subfolder for README files while knitting updates "README.md" which is what we want for a good package landing page
2. Less important (for now) but on the horizon: increases the repo size on GitHub and may make the package bigger too (even though in theory the website content is all listed in the `.Rbuildignore`)

## Sub-tasks

- [x] Create new repo for the website ('dndR-website'?)
- [x] Move all website content into that one
- [x] Set up website building from that new repo
    - [x] Replace link in description for _both_ repos with the new website link
- [x] Delete website content from package repo
    - [x] Turn off page building in settings of package repo
- [x] Add page to website for `party_diagram`!
    - Remember to crosslink with Tim's website and thank him (as I do in the README currently)

**Comment by njlyon0** [comment]
## Update - Website repo created!

- Standalone website repo created see [njlyon0/dndR-website](https://github.com/njlyon0/dndR-website)
- Migrated most content over but my wifi is not good right now so I can't test if the website will build right this moment

**Comment by njlyon0** [comment]
## Update - Page built

Decided to risk it and it looks like the page built correctly! Some final checks remain though:

## Remaining Tasks

-  [x] Update `dndR` on my computer so that the website repo can run the `party_diagram` code chunks (it's version of `dndR` doesn't include that package
    - [x] Remember to re-render the site after updating `dndR`!!
 - [x] Update `roxygen2` and re-document `dndR` to remove the dialogue about it AND re-check the R package via GitHub's R-CMD check (two birds...)
 - [x] Once everything works, close the original `party_diagram` issue (see here: https://github.com/njlyon0/dndR/issues/5)

**Comment by njlyon0** [comment]
## Done!

Accomplished all tasks and am good to go!
